id: P287F972E
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG12969
  instance_id: http://purl.bdrc.io/resource/IE1KG12969
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བཀའ་བརྒྱུད་བསྟན་སྲུང་རྒྱ་མཚོའི་འཕྲིན་ལས་ཀྱི་ཆོ་ག་དོན་གཉིས་ལྷུན་གྲུབ།
  alt_title: {}
  author: None
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    e73ab35cb61d421db144be88641388f3:
      title: པོད ༡་བཀའ་བརྒྱུད་བསྟན་སྲུང་རྒྱ་མཚོའི་འཕྲིན་ལས་ཀྱི་ཆོ་ག་དོན་གཉིས་ལྷུན་གྲུབ།
      volume_number: 1
      base_file: UT1KG12969_I1KG13582_0000.txt
      reference: http://purl.bdrc.io/resource/VLCEB6093A03D8EC1E
      image_group: I1KG13582
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG12969
  - http://purl.bdrc.io/resource/MW1KG12969
  ocr_software: Namsel
created_at: '2021-12-22T10:33:04.075574'
last_modified_at: '2021-12-22T10:33:04.075581'
statistics:
  total_words: 49787
  total_non_words: 8695
quality:
  non_words_ratio: 0.17
